version: 0.0
os: linux

files:
  - source: backend/
    destination: /opt/chinook/backend

hooks:
  BeforeInstall:
    - location: backend/scripts/stop_server.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: backend/scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: backend/scripts/start_server.sh
      timeout: 300
      runas: ubuntu
